### ISSUE TITLE
Refuses to open[BUG]

### ISSUE THREAD

**Issue by HomerTheGeek** [jtsage/FS19_Mod_Checker#56]
**Describe the bug**
Clicking icon indicates the program has started but nothing opens and the app cannot be switched to. Both portable and installed version behave the same. 

**To Reproduce**
1. Go to 'the program'
2. Click on 'it'

**Expected behavior**
Program should open and that is not happening

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2

**Additional context**

**Comment by jtsage** [comment]
I can try and run a newer build of this one, not sure when I'm gonna get time to do it - but if you've not found it already, this has been pretty much superseded with https://github.com/FSGModding/FSG_Mod_Assistant

My guess at a glance at the "Win 11" OS is that the version of electron this was last built on doesn't play nice.

**Comment by HomerTheGeek** [comment]
Thanks for the quick reply

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
